FROM mysql:8.0.31
LABEL Author = Tarun
LABEL Version = 15
EXPOSE 3306
ENV MYSQL_ROOT_PASSWORD = mysql
ENV MYSQL_DATABASE = mysql_db
ENV MYSQL_USER = mysql_user
ENV MYSQL_PASSWORD = mysql_password
CMD ["mysqld"]